# Node.js with React

# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# - task: AzureStaticWebApp@0
#   inputs:
#     app_build_command: 'npm run build'
#     output_location: '/dist'
#     skip_app_build: false
#     skip_api_build: true
#     is_static_export: false
#     azure_static_web_apps_api_token: '19db63e726b896f8abaa9928f4251b790ffc3afa0befdf738e9fea42bde5a08f5-0ff97b69-69ea-43f3-b020-a696ae295407000160682'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'npm run build'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'thecoconut.com.au(967fc952-c14d-437c-9651-2456c52acf13)'
    appType: 'webAppLinux'
    WebAppName: 'thecoconut-web'
    packageForLinux: 'drop'
    RuntimeStack: 'NODE|18-lts'